### PR TITLE
User story 8 is completed

### PR DESCRIPTION
**Pull request by AbbosB12**
User story 8 is completed, please review the my code.

### CODE REVIEW

**Review by blishchenko1981 — APPROVED** [review]
Good job Abbos, Looks great!

**Review by blishchenko1981 — APPROVED** [review]

**Review by Sabirindev — APPROVED** [review]
i just check you code, it looks dangerous ;)))) great bro as always

**Comment by KseniiaMazanko** [comment]
Great job Abbos! Nice and clean code, love it!

**Review by KseniiaMazanko — APPROVED** [review]

**Comment by KseniiaMazanko** [comment]
Good to merge!

**Pull request merged**
