### PR TITLE
User story 6 completed, Page and Test created, bug found

### PR DESCRIPTION
**Pull request by KseniiaMazanko**
Waiting for the approval

### CODE REVIEW

**Comment by blishchenko1981** [comment]
Good job

**Review by blishchenko1981 — APPROVED** [review]

**Review by AbbosB12 — APPROVED** [review]
Good started. Your code is great.

**Review by Sabirindev — APPROVED** [review]
I have checked your code and approved

**Comment by AbbosB12** [comment]
Your code is very to merge.

**Pull request merged**
